### ISSUE TITLE
Epic: New item type Effect to represent temporary Active Effects

### ISSUE THREAD

**Issue by hlmodking** [Muttley/foundryvtt-shadowdark#276]
A way to allow Foundry Active Effects. 
Initially backend (Macros and Calls) and possibly client facing at some point. 

Would help with all kinds of buffs and magic related boons/banes.

Cheers!

**Comment by bakbakbakbakbak** [comment]
Can you elaborate a bit on this?

We do support Active Effects (we use them in talents), but I assume that is not what you're asking for?

**Comment by bakbakbakbakbak** [comment]
I'm going to go out on a limb and assume this is about having Effects being applicable onto actors. It looks like the PF2e has a very neat implementation of this, where it shows up on the interface what buffs you have et.c.

I'm thinking of introducing a new Effect item that applies effects temporarily.

**Comment by hlmodking** [comment]
Thats exactly what I ment. Apologies for the confusion.

Applying temporary active effects to actors. Thank you!

**Comment by bakbakbakbakbak** [comment]
Implementation done:
- [ ] Effect Overhaul
  - [ ] Add new Item type: Effect
  - [ ] Predefined Effect from `json` file
  - [ ] Implement Effects into `ItemSheetSD` and `ItemSD` directly
  - [ ] Add DataList selector instead of App (Item Properties)
  - [ ] Add Duration tracking based on Game Time
  - [ ] Add Turn/Round tracking
  - [ ] Add Duration tracking based on World Time
  - [ ] Add automatic cleanup of expired effects
  - [ ] Add automatic ActiveEffect duration setting for showing effect on Token image
  - [ ] Add setting flags for showing effect on Panel & Token
  - [ ] Add interface for effects on
    - [ ] Player
    - [ ] NPC
    - [ ] Items (Magic Item / Talent)
- [ ] Effect Panel App
  - [ ] Add Effect Panel based on DFreds Effect Panel
  - [ ] Add visual duration tracking
  - [ ] Add setting to allow showing passive effects
- [ ] Testing

Left to implement (as a reminder to self):
- [ ] Migrations
  - [ ] Schema updates
  - [ ] Migrating pre-existing items to new version
- [ ] Testing
  - [ ] Effects requiring user input (Weapon Mastery e.g.)
  - [ ] Auto-removal of effects (Probably won't do this though)
- [ ] Effect types
  - [ ] Lightsource effects with pre-defined light templating
- [ ] Update current compendium items
  - [ ] Update Spells to provide Spell Effect-effect items
    - [ ] Create effects
    - [ ] Update descriptions
  - [ ] Update Roll Tables with effects
  - [ ] Update Talents (Do we need this?)
    - [ ] Create Effects
    - [ ] Update descriptions
  - [ ] Update Magic Items
- [ ] Add Glowing Purple & Immersed in Darkness effects (QS Page 54)
